Stat svc
Rolik8797/java-explore-with-me pull request #1
Opened 2023-11-18 08:25 UTC by Rolik8797

2023-11-19 01:25 UTC, NikolaiDem requested changes

2023-11-19 01:25 UTC, NikolaiDem commented on stats-server/pom.xml
> +        <version>0.0.1-SNAPSHOT</version>
${project.version}

2023-11-19 01:25 UTC, NikolaiDem commented on stats-server/stats-server-client/src/main/java/ru/practicum/ErrorHandler.java
> +public class ErrorHandler {
Лучше логировать все исключения

2023-11-19 01:25 UTC, NikolaiDem commented on stats-server/stats-server-dto/src/main/java/ru/practicum/EndpointHit.java
> +@Data
Лучше не использовать вместе аннотации, по которым генерятся одинаковые структуры (в данном случае конструкторы), чтобы не возникало потенциальных конфликтов. Поэтому, если нужен билдер, то вместо @Data можно отдельно вытащить геттеры, сеттеры и что еще необходимо.
Аналогично для остальных классов

2023-11-19 01:25 UTC, NikolaiDem commented on stats-server/stats-server-dto/src/main/java/ru/practicum/EndpointHit.java
> +    @NotNull(message = "Необходимо указать идентификатор сервиса")
NotNull не нужен, если есть NotBlank
Аналогично для остальных полей

2023-11-19 01:25 UTC, NikolaiDem commented on stats-server/stats-server-service/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
${project.version}

2023-11-19 01:25 UTC, NikolaiDem commented on stats-server/stats-server-service/src/main/resources/schema.sql
> +
Еще лучше сделать таблицу с приложениями, где будет его id и название. Таким образом при изменении, например, названия приложения не придется обновлять всю таблицу hits.

2023-11-22 13:41 UTC, Rolik8797 commented on stats-server/stats-server-client/src/main/java/ru/practicum/ErrorHandler.java
> +public class ErrorHandler {
исправила

2023-11-22 13:42 UTC, Rolik8797 commented on stats-server/stats-server-dto/src/main/java/ru/practicum/EndpointHit.java
> +@Data
исправила

2023-11-22 13:42 UTC, Rolik8797 commented on stats-server/stats-server-dto/src/main/java/ru/practicum/EndpointHit.java
> +    @NotNull(message = "Необходимо указать идентификатор сервиса")
убрала

2023-11-22 13:43 UTC, Rolik8797 commented on stats-server/stats-server-service/src/main/resources/schema.sql
> +
POSTMAN не согласен с таким решением, что бы я не делала

2023-11-22 13:43 UTC, Rolik8797 commented on stats-server/stats-server-service/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
у меня это не работает

2023-11-22 13:44 UTC, Rolik8797 commented on stats-server/pom.xml
> +        <version>0.0.1-SNAPSHOT</version>
у меня это не работает

2023-11-22 13:44 UTC, Rolik8797 commented
ТЗ2

2023-11-23 08:15 UTC, merged