Main svc
Rolik8797/java-explore-with-me pull request #4
Opened 2023-11-26 07:39 UTC by Rolik8797

2023-11-27 18:23 UTC, NikolaiDem requested changes

2023-11-27 18:23 UTC, NikolaiDem commented on main-service/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
${project.version}
Аналогично для остальных зависимостей со snapshot

2023-11-27 18:23 UTC, NikolaiDem commented on main-service/src/main/java/ru/practicum/category/CategoryAdminServiceImp.java
> +    @Transactional
Аннотацию можно вынести на уровень класса. Аналогично для остальных сервисов

2023-11-27 18:23 UTC, NikolaiDem commented on main-service/src/main/java/ru/practicum/compilation/controller/CompilationAdminController.java
> +    public CompilationDto create(@Validated @RequestBody NewCompilationDto newCompilationDto) {
Для RequestBody обычно используется Valid.
Аналогично для остальных контроллеров

2023-11-27 18:23 UTC, NikolaiDem commented on main-service/src/main/java/ru/practicum/compilation/controller/CompilationAdminController.java
> +@Validated
Аннотация необходима, если в аргументах методов контроллера используются аннотации валидации (например, Positive, NotEmpty и т.д.).
Аналогично для остальных контроллеров

2023-11-27 18:23 UTC, NikolaiDem commented on main-service/src/main/java/ru/practicum/event/EventAdminService.java
> +    List<EventFullDto> get(List<Long> users, List<String> states, List<Long> categories,
Все аргументы метода лучше вынести в отдельный dto. Хорошей практикой является создание методов максимум с 2-3 аргументами

2023-11-27 18:23 UTC, NikolaiDem commented on main-service/src/main/java/ru/practicum/event/EventAdminServiceImp.java
> +            return newEvents.stream().map(EventMapper::eventToEventFullDto).collect(Collectors.toList());
List<Event> eventsAddViews = processingEvents.addViewsInEventsList(events, request);
            List<Event> newEvents = processingEvents.confirmRequests(eventsAddViews);
            return newEvents.stream().map(EventMapper::eventToEventFullDto).collect(Collectors.toList());

этот код дублируется с веткой else

2023-11-27 18:23 UTC, NikolaiDem commented on main-service/src/main/java/ru/practicum/event/EventPrivateServiceImp.java
> +    public List<ParticipationRequestDto> getRequests(Long userId, Long eventId, HttpServletRequest request) {
Метод больше подходит для RequestPrivateServiceImp

2023-11-27 18:23 UTC, NikolaiDem commented on main-service/src/main/java/ru/practicum/event/EventPrivateServiceImp.java
> +                    requestRepository.save(requestList);
Вместо сохранения в цикле лучше после него вызывать у репозитория метод saveAll.
Аналогично для else ветки

2023-11-27 18:23 UTC, NikolaiDem commented on main-service/src/main/java/ru/practicum/event/EventPrivateServiceImp.java
> +            requestRepository.save(requestList);
Вместо сохранения в цикле лучше после него вызывать у репозитория метод saveAll.

2023-11-27 18:23 UTC, NikolaiDem commented on main-service/src/main/java/ru/practicum/event/model/Event.java
> +    private Long views;
Это поле в Event не нужно, потому что между Event и Request уже существует связь один ко многим (    CONSTRAINT fk_event_id FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE).
И не нужно будет обновлять событие каждый раз при подтверждении или отклонении запроса.
Посчитать количество подтвержденных запросов можно будет обычным джойном (при запросе всех событий)

2023-11-27 18:23 UTC, NikolaiDem commented on statistic-service/stats-server/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS endpoint_hit
Еще лучше сделать таблицу с приложениями, где будет его id и название. Таким образом при изменении, например, названия приложения не придется обновлять всю таблицу endpoint_hit.

2023-11-27 18:23 UTC, NikolaiDem commented on main-service/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users(
Выровнять отступы

2023-11-28 13:46 UTC, Rolik8797 commented on main-service/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
добавила

2023-11-28 13:46 UTC, Rolik8797 commented on main-service/src/main/java/ru/practicum/category/CategoryAdminServiceImp.java
> +    @Transactional
вынесла

2023-11-28 13:46 UTC, Rolik8797 commented on main-service/src/main/java/ru/practicum/compilation/controller/CompilationAdminController.java
> +    public CompilationDto create(@Validated @RequestBody NewCompilationDto newCompilationDto) {
исправила

2023-11-28 13:47 UTC, Rolik8797 commented on main-service/src/main/java/ru/practicum/compilation/controller/CompilationAdminController.java
> +@Validated
оставила где необходимо

2023-11-28 13:47 UTC, Rolik8797 commented on main-service/src/main/java/ru/practicum/event/EventAdminService.java
> +    List<EventFullDto> get(List<Long> users, List<String> states, List<Long> categories,
перенесла в dto

2023-11-28 13:48 UTC, Rolik8797 commented on main-service/src/main/java/ru/practicum/event/EventAdminServiceImp.java
> +            return newEvents.stream().map(EventMapper::eventToEventFullDto).collect(Collectors.toList());
поправила

2023-11-28 13:49 UTC, Rolik8797 commented on main-service/src/main/java/ru/practicum/event/EventPrivateServiceImp.java
> +    public List<ParticipationRequestDto> getRequests(Long userId, Long eventId, HttpServletRequest request) {
Postman считает , что этому методу там самое место)

2023-11-28 13:49 UTC, Rolik8797 commented on main-service/src/main/java/ru/practicum/event/EventPrivateServiceImp.java
> +                    requestRepository.save(requestList);
поправила

2023-11-28 13:49 UTC, Rolik8797 commented on main-service/src/main/java/ru/practicum/event/EventPrivateServiceImp.java
> +            requestRepository.save(requestList);
поправила

2023-11-28 13:50 UTC, Rolik8797 commented on main-service/src/main/java/ru/practicum/event/model/Event.java
> +    private Long views;
удалила  ( CONSTRAINT fk_event_id FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE).

2023-11-28 13:50 UTC, Rolik8797 commented on statistic-service/stats-server/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS endpoint_hit
Postman все еще не согласен

2023-11-28 13:51 UTC, Rolik8797 commented on main-service/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users(
выровня(и)ла

2023-11-28 13:51 UTC, Rolik8797 commented
ТЗТЗТЗ

2023-11-29 20:27 UTC, NikolaiDem commented on main-service/src/main/java/ru/practicum/category/CategoryAdminServiceImp.java
> +    @Transactional
@Transactional лучше применять для модифицирующих запросов, а @Transactional(readOnly = true) для запросов. Аналогично для других сервисов.

2023-11-29 23:32 UTC, NikolaiDem commented on main-service/src/main/java/ru/practicum/event/EventAdminServiceImp.java
> +            events = eventRepository.findAllByAdmin(filterDto.getUsers(), filterDto.getStates(), filterDto.getCategories(), newRangeStart, newRangeEnd, filterDto.getFrom(), filterDto.getSize());
Лучше передать только filterDto вместо большого количества параметров

2023-11-29 23:32 UTC, NikolaiDem commented on main-service/src/main/java/ru/practicum/event/EventAdminServiceImp.java
> +            events = eventRepository.findAllByAdminAndState(filterDto.getUsers(), null, filterDto.getCategories(), newRangeStart, newRangeEnd, page);
Лучше передать только filterDto вместо большого количества параметров

2023-11-29 23:32 UTC, NikolaiDem commented on main-service/src/main/java/ru/practicum/event/EventPrivateServiceImp.java
> +    public List<ParticipationRequestDto> getRequests(Long userId, Long eventId, HttpServletRequest request) {
А какое к этому имеет отношение Postman?

2023-11-29 23:32 UTC, NikolaiDem commented on main-service/src/main/java/ru/practicum/event/EventPrivateServiceImp.java
> +                    requestRepository.saveAll(requests);
Вызвать saveAll() нужно после цикла

2023-11-29 23:32 UTC, NikolaiDem commented on main-service/src/main/java/ru/practicum/event/EventPrivateServiceImp.java
> +                    requestRepository.saveAll(requests);
Вызвать saveAll() нужно после цикла

2023-11-29 23:32 UTC, NikolaiDem commented on statistic-service/stats-server/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS endpoint_hit
С чем?

2023-11-29 23:36 UTC, NikolaiDem requested changes

2023-11-29 23:36 UTC, NikolaiDem commented on main-service/src/main/java/ru/practicum/event/model/Event.java
> +    private Long views;
Это напрасно) Нужно вернуть как было. И перенести все транзиентные поля в dto

2023-12-01 11:03 UTC, Rolik8797 commented on main-service/src/main/java/ru/practicum/category/CategoryAdminServiceImp.java
> +    @Transactional
рассортировала

2023-12-01 11:04 UTC, Rolik8797 commented on main-service/src/main/java/ru/practicum/event/EventPrivateServiceImp.java
> +    public List<ParticipationRequestDto> getRequests(Long userId, Long eventId, HttpServletRequest request) {
Перенесла

2023-12-01 11:04 UTC, Rolik8797 commented on main-service/src/main/java/ru/practicum/event/model/Event.java
> +    private Long views;
вернула ( CONSTRAINT fk_event_id FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE).

2023-12-01 11:05 UTC, Rolik8797 commented on statistic-service/stats-server/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS endpoint_hit
добавила

2023-12-01 11:08 UTC, Rolik8797 commented
[ТЗТЗТЗТЗТЗТЗ]

2023-12-02 14:18 UTC, NikolaiDem approved these changes
Работа принята с большим техдолгом. Большой пул замечаний исправлен не был

2023-12-02 14:32 UTC, merged